services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromService:
          type: mysql
          name: laravel-db
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: laravel
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        generateValue: true
